### ISSUE TITLE
Question: Why not automate containers_to_keep_running by list_dataset_or_folders?

### ISSUE THREAD

**Issue by jaddel** [SpaceinvaderOne/Unraid_ZFS_Auto_Dataset_Update#5]
Hi Ed, many thanks for all the great work you put into teaching and explaing things about unraid. 

May I ask why don't you auto generate the containers_to_keep_running arry by e.g the other [list_datasets_or_folders](https://github.com/SpaceinvaderOne/list_datasets_or_folders) script you did?

**Comment by SpaceinvaderOne** [comment]
Hi @jaddel I considered automating the process to determine which containers are active and verifying if their appdata has been converted. If not, the script would halt the container; if it has, the script would proceed without stopping it. However, not every running container has an appdata folder that corresponds to its actual name. Given this inconsistency, I felt it was better to leave this as a manual decision.

**Comment by SpaceinvaderOne** [comment]
Auctually i have thought of a way to examine the appdata paths from the docker bind mounts and check if they are datasets already. So i will be able to automate shutdown of only the containers not converted :)

Should have it push tomorrow

**Comment by jaddel** [comment]
Very cool, thanks for picking this up! :)

**Comment by samssausages** [comment]
I just made a similar modification to the script and ran into the same issue, what if the container name and folder/dataset name don't match.
I was about to expand on that function by adding some sort of check for the containers actual volumes and mount points, when I found this request.

I look forward to seeing how you are handling this @SpaceinvaderOne 
I can help to try and make this work if needed, just let me know if you need more eyeballs looking at it!

Thanks for the script!

**Comment by SpaceinvaderOne** [comment]
New script is available now :)
After many hours finally got some new functions working. [Its a separate script for now.](https://github.com/SpaceinvaderOne/Unraid_ZFS_Auto_Dataset_Update/blob/main/ZFS_Auto_Dataset_Update_Advanced.sh) The script now can handle multiple datasets, auto shutting down containers and vms and various safety checks etc.

**Regular datasets**
For datasets that aren't designated as "appdata" or "vms", add their paths to source_datasets_array. There's no limit on how many datasets you can add.

**Appdata and vm datasets**
Do not add the paths of "appdata" or "vms" datasets directly to the array. Instead:

Specify whether you want to process appdata or vms by setting their respective variables to "yes".
Define the locations for appdata and vms by setting their corresponding variables.

The script will then automatically incorporate these paths into the source_datasets_array for processing.

`Processing containers`, the script can tell if the running container's appdata is already in a dataset. If they are, it will leave that container running. Otherwise, the container will be stopped in preparation for conversion.

`Processing vms` , again the same. if their vdisks are already in a zfs dataset they will be left running. Otherwise shut down for conversion

Once these checks and shutdowns (if needed) are finished, the script will convert regular folders in the source locations into zfs datasets. Then it  will restart any stopped containers and vms and then display a summary of the converted datasets.

 @samssausages  Yes, I used the same approach as you outlined. For the containers, I utilized docker inspect, and for the vms vdisks, I used virsh domblklist. Then logic to translate the location to an actual path when the location appeared to be a union, like /mnt/user. I then cross-referenced this with the source to check if the location already existed as a dataset. Handling spaces within the data was a real PIA. However, everything now appears to be functioning correctly. Thanks for offering help. I wish I had come across your message earlier!
 
 But please @jaddel and @samssausages  if you would  test the script and let me know if you have any issues i would really appreciate it. When i am sure all is good i will deprecate the old script. Thanks :)

**Comment by samssausages** [comment]
@SpaceinvaderOne I'll try it out this week!  Thanks for all the hard work!
